Repository logstash-plugins/logstash-output-http, pull requests merged in 2022-03, with the labels that each got.

#130 [Doc] clarify retry loop
  CHANGELOG.md
  docs/index.asciidoc
  logstash-output-http.gemspec
Labels: status:changes-requested

#129 Fix retry indefinitely in termination process
  CHANGELOG.md
  docs/index.asciidoc
  lib/logstash/outputs/http.rb
  spec/outputs/http_spec.rb
Labels: int-shortlist, status:approved

#131 Feat: added `ssl_supported_protocols` option
  CHANGELOG.md
  docs/index.asciidoc
  lib/logstash/outputs/http.rb
  logstash-output-http.gemspec
  spec/outputs/http_spec.rb
  spec/spec_helper.rb
Labels: status:approved
